# Page settings
baseurl                 = "localhost:1313"
title                   = "SFU Science Frosh 2017"
languageCode            = "en-us"
theme                   = "hugo-elate-theme"

[params]
  
  custom_css            = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author                = ""
  description           = ""
  email                 = ""
  # Navigation
  [params.navigation]
    brand               = "Elate"
    home                = "Home"
    work                = "Work"
    testimonials        = "Testimonials"
    services            = "Events"
    about               = "About"
    contact             = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title               = "test"
    subtitle            = ''
    img                 = '/images/MainPage_Main.png'
    parallax            = 0.4

  [params.intro]
  img='GirlsTag.jpg'

  [[params.intro.item]]
    button              = "About"
    description         = "The SFU Science frosh has a deep, storied history."
    url                 = "#"
    icon                 = "/images/Icon_Saturn.png"

  [[params.intro.item]]
    button              = "Get Info"
    description         = "You got Q, we got A - put it together and you got a website"
    url                 = "#fh5co-services"
    icon                 = "/images/Icon_Jupiter.png"

  [[params.intro.item]]
    button              = "Register"
    description         = "everyone else is coming, if you don't come you're probably a nobody"
    url                 = "#"
    icon                 = "/images/Icon_Earth.png"

  [params.services]
    enable              = true
    title               = "Events"
    description         = "lots"

  [[params.services.item]]
    title               = "hello"
    description         = "1234"
    icon                 = "Icon_Earth.png"

  [[params.services.item]]
    title               = "hell"
    description         = "124"
    icon                 = "Icon_Earth.png"

  [[params.services.item]]
    title               = "hel"
    description         = "12"
    icon                 = "Icon_Earth.png"

  [params.countdown]
    enable              = true
    title               = "test"
    background          = "full_image_1.jpg"

  # Counters section
  [params.counters]
    enable              = false
    title               = "Stats"
    background          = "full_image_1.jpg"

    [[params.counters.item]]
      description       = "New SFU Science Students"
      icon              = "icon-briefcase"
     from               = 0
      to                = 300
      interval          = 100
      speed             = 5000

    [[params.counters.item]]
      description       = "Spots in Science Frosh"
      icon              = "icon-code"
      from              = 0
      to                = 150
      interval          = 50
      speed             = 5000

    [[params.counters.item]]
      description       = "Spots in Science Frosh Taken"
      icon              = "icon-cup"
      from              = 0
      to                = 149
      interval          = 50
      speed             = 5000


  # Footer section
  [params.footer]
    enable              = true
    copyright           = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
